name: exercism_dart
environment:
  sdk: '>=2.0.0 <3.0.0'
authors:
  - SuperPaintman <SuperPaintmanDeveloper@gmail.com>
  - Stargator <wildbug@linuxmail.org>
  - fwip
  - devkabiir
  - jvarness <jake.varness@gmail.com>
dependencies:
  args: '^1.0.0'
  io: '^0.3.0'
  logging: '^0.11.3+2'
  yaml: '^2.1.12'
dev_dependencies:
  dart_style: '^1.0.8'
  mockito: '^4.0.0'
  test: '>=0.12.24+8 <2.0.0'
