name: Links

on:
  pull_request:
    paths:
#      - '.github/workflows/links.yml' Temporarily disabled by @Stargator
      - 'concept/**/*.md'
      - 'concept/**/links.json'
      - 'docs/*.md'
#      - 'exercises/**/*.md' Temporarily disabled by @Stargator
      - 'reference/*.md'
      - '*.md'
      - '**/**/*.md'
      - '**/*.md'

  repository_dispatch:
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --require-https .
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
